#!/bin/bash

if [ $# == 0 ]; then
  echo "you must tell me which service you use: $0 all or $0 server"
  exit -1
fi

if [ $1 == "all" ];then
  #ln -f -s localrc_server_aio_template localrc_server_template
  cat localrc_server_template
elif [ $1 == "server" ];then 
  #ln -f -s localrc_server_only_template localrc_server_template
  cat localrc_server_template
else
  echo "you should tell me which service you use: $0 all or $0 server"
fi
[ -f ./imroot ] && ./imroot
sudo debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password password gadmei'
sudo debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password_again password gadmei'

[ -d ./deb ] && ( sudo dpkg -i ./deb/*.deb && mv ./deb ./deb_used )

X7WORKDIR=`pwd`
CONFDIR=$X7WORKDIR/conf
CURWD=$X7WORKDIR


# setup sources.list and use local deb only
if [ -d $CURWD/ubuntu_repo ]; then
  cp -f $CONFDIR/etc/apt/sources.list.template $CONFDIR/etc/apt/sources.list
  sed -i "s|%HOSTADDR%|127.0.0.1|g" $CONFDIR/etc/apt/sources.list
  if [ ! -f /etc/apt/sources.list.backup ]; then
    sudo mv -f /etc/apt/sources.list /etc/apt/sources.list.backup
  fi
  sudo cp -f $CONFDIR/etc/apt/sources.list /etc/apt/sources.list 
  cd $CURWD/x7http
  cp x7srv.conf.template lighttpd.conf
  sed -i "s|%SRVDOCROOT%|$CURWD/ubuntu_repo|g" $CURWD/x7http/lighttpd.conf
  killall lighttpd || true
  ./lighttpd -f lighttpd.conf -m lib
  cd $CURWD
fi


sudo rabbitmqctl  -q change_password guest guest


./startup_2.sh eth0
INTERFACE=eth0 source ./addrc
echo "nameserver $GATEWAY" | sudo tee -a /etc/resolv.conf >/dev/null

if [ $1 == "all" ];then
  sudo mount -t nfs4 -o noatime 127.0.0.1:/ /opt/stack/nova/instances
fi

