#!/bin/bash

X7WORKDIR=`pwd`
CONFDIR=$X7WORKDIR/conf
CURWD=$X7WORKDIR

# download dependency for git, rabbitmq, etc
#sudo apt-get update
#sudo apt-get install -y --assume-yes approx

# setup sources.list and use local deb only
if [ -d $CURWD/ubuntu_repo ]; then
  cp -f $CONFDIR/etc/apt/sources.list.template $CONFDIR/etc/apt/sources.list
  sed -i "s|%HOSTADDR%|127.0.0.1|g" $CONFDIR/etc/apt/sources.list
  if [ ! -f /etc/apt/sources.list.backup ]; then
    sudo mv -f /etc/apt/sources.list /etc/apt/sources.list.backup
  fi
  sudo cp -f $CONFDIR/etc/apt/sources.list /etc/apt/sources.list 
  cd $CURWD/x7http
  cp x7srv.conf.template lighttpd.conf
  sed -i "s|%SRVDOCROOT%|$CURWD/ubuntu_repo|g" $CURWD/x7http/lighttpd.conf
  killall lighttpd || true
  ./lighttpd -f lighttpd.conf -m lib
  cd $CURWD
fi

# approx setup
#cp -f $CONFDIR/etc/approx/approx.conf.template $CONFDIR/etc/approx/approx.conf
#sudo cp -f $CONFDIR/etc/approx/approx.conf /etc/approx/approx.conf
#sudo apt-get update
# approx through inetd
#sudo inetd
sudo apt-get update

# installn dependent package, ignore signature warning
sudo apt-get install -y --force-yes git rabbitmq-server  python-kombu python-django python-paramiko python-setuptools unzip

# setup rabbitmq, change password of guest to guest
sudo rabbitmqctl  -q change_password guest guest

# init queue used by x7
$CURWD/create_queue

./mq_receiver.py &
# start x7web here!!
echo "open browser with url http://IPADDR:8000/init"
echo "availabie IPADDR is: "

ifconfig |  grep 'inet addr:' |cut -d: -f2 | awk '{ print $1}'

python x7_start/manage.py runserver 0.0.0.0:8000 1>/dev/null 2>/dev/null
